### ISSUE TITLE
Build GeoTriples

### ISSUE THREAD

**Issue by LukeKaim** [LinkedEOData/GeoTriples#4]
I am trying to build using windows 10 64 bit. This command is not working java -jar target/geotriples-<version>-cmd.jar. I am not sure what I am doing wrong.

**Comment by dimitrianos** [comment]
Please download GeoTriples at: http://linkedeodata.github.io/GeoTriples/geotriples-1.1.6-SNAPSHOT-bin.zip
We provide Windows (.bat) as well as Unix scripts.
